#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail


main () {
    curator --config="{{ runtime_dir }}/curator.yml" "{{ runtime_dir }}/runtime/elasticsearch/curator-action-expire-indexes.yml"
}


main "$@"
